Add readme
nagomuohta/freemarket_sample_43d pull request #2
Opened 2019-01-29 12:02 UTC by nagomuohta

[WIP]
READMEの実装

#WHY
今回作成したREADMEを元にデータベース設計を行うため。

#WHAT
今後のテーブルの作成、動向に関する記述がされている。

2019-01-29 12:09 UTC, ReoKuriyama requested changes

2019-01-29 12:09 UTC, ReoKuriyama commented on README.md
> +- has_one :user_address, dependent: destroy
userテーブルがuser_addressをhas_oneですかね。。？

2019-01-29 12:09 UTC, ReoKuriyama commented on README.md
> +|proceed|integer||
`proceed`とはどのようなカラムになりますか？

2019-01-29 12:09 UTC, ReoKuriyama commented on README.md
> +|product_state|integer|null: false, foreign_key: true|
belongs_toに書いてあるものの外部キーがないように見えます 👀

2019-01-29 12:55 UTC, nagomuohta commented on README.md
> +- has_one :user_address, dependent: destroy
userレコードが消された時に、user_addressも同時に消すような記述にしたくてdependentオプションを付けているのですが、不要でしょうか。。？

2019-01-29 12:55 UTC, nagomuohta commented on README.md
> +|proceed|integer||
売上金のカラムだったのですが、バックログを再度確認したら必要ないようですので消させて頂きました！

2019-01-29 12:57 UTC, nagomuohta commented on README.md
> +|product_state|integer|null: false, foreign_key: true|
外部キーの認識が間違っていたみたいですので、修正させて頂きました！
大変お手数ですが、もう一度ご確認お願いいたします！

2019-01-29 13:23 UTC, ReoKuriyama reviewed
おそらくpushされてないです

2019-01-29 13:23 UTC, ReoKuriyama commented on README.md
> +- has_one :user_address, dependent: destroy
すみません記述ミスです　user_addressテーブルに`has_one :user_address`が書いてあります

2019-01-30 00:50 UTC, nagomuohta commented on README.md
> +- has_one :user_address, dependent: destroy
こちらこそ言われるまで気づけずにすみません、修正いたしましたのでご確認お願いいたします！
また、外部キーの修正に関しましてはpushのタイミングを間違えていたようです。お手数ですが、下記のURLに修正されたcommitがございますのでご確認お願いいたします！
https://github.com/nagomuohta/freemarket_sample_43d/pull/2/commits/eea64f76101e3edcd0b2d4a4ab2f15ae8325ad4b

2019-01-30 02:01 UTC, hzak2xx approved these changes
LGTMです

2019-01-30 02:42 UTC, merged