Add users_registration
nagomuohta/freemarket_sample_43d pull request #26
Opened 2019-02-05 12:50 UTC by nagomuohta

[WIP]ユーザー登録画面の実装

# WHAT
ユーザー登録に必要なviewと、それぞれのページ遷移によるユーザーの居所を示すボーダーの作成

# WHY
登録に必要な情報を入力して頂くとともに、ユーザーが今どこにいるかを確認出来るようにする為。

実装画面は以下に添付いたします、ご確認ください。
https://gyazo.com/c16acf46fc31df4b7bb86beabd88f5ce

2019-02-05 13:00 UTC, ReoKuriyama requested changes

2019-02-05 13:00 UTC, ReoKuriyama commented on app/assets/stylesheets/layout/_headersigninone.scss
> +      ol.users_signin_form_ol{
&が使えそうですね 👀

2019-02-05 13:00 UTC, ReoKuriyama commented on app/assets/stylesheets/layout/_headersigninone.scss
> +      ol.users_signin_form_ol{
これ以降も使えるところが多々みられます

2019-02-05 13:00 UTC, ReoKuriyama commented on app/views/products/index.html.haml
> +        = image_tag "スクリーンショット 2019-02-02 8.22.34.png", class: 'topscroll-image'
ファイル名変えましょう

2019-02-05 13:00 UTC, ReoKuriyama commented on app/views/users/_headersigninfive.html.haml
> +%header.users_signin_form_header
この`headersigninfive` と`headersigninfore` の違いは何でしょうか？

2019-02-05 13:00 UTC, ReoKuriyama commented on config/routes.rb
> +      get 'signinone'
このようなルーティングは明らかによくないのでこうなったしまった原因と実装したい内容をご教授ください

2019-02-06 01:40 UTC, nagomuohta commented on app/assets/stylesheets/layout/_headersigninone.scss
> +      ol.users_signin_form_ol{
ご指摘頂いた部分に関しましては、修正を入れた所以下のようにずれが生じてしまいましたので、他の修正が可能な部分を修正させて頂きました。ご確認お願いいたします。
https://gyazo.com/333c52b80239b3f6732307a2f2f3b643

2019-02-06 01:40 UTC, nagomuohta commented on app/views/products/index.html.haml
> +        = image_tag "スクリーンショット 2019-02-02 8.22.34.png", class: 'topscroll-image'
修正いたしました。

2019-02-06 01:45 UTC, nagomuohta commented on app/views/users/_headersigninfive.html.haml
> +%header.users_signin_form_header
ユーザーの現在のページを示しています。
headersigninfive
https://gyazo.com/49b4816a528029d7a6fc13619b99c6de

headersigninfore
https://gyazo.com/d36afc70b153378f1afd95e94f5d1a9f

2019-02-06 01:48 UTC, nagomuohta commented on config/routes.rb
> +      get 'signinone'
大変失礼いたしました。
こちらは作業中に実装画面の確認の為、仮置きしていたもので、本来このようなルーティングはございません。
実装内容といたしましては、ページを順番に遷移させるような内容になっております。

2019-02-06 02:11 UTC, TOMARUMARU commented on app/views/users/_headersigninfive.html.haml
> +%header.users_signin_form_header
foreは数字のfourのことですかね？
何れにせよfive, fourだとかなりわかりづらいですね。
他の命名を考えましょう！

2019-02-06 02:11 UTC, TOMARUMARU reviewed
返信しましたのでご確認ください

2019-02-06 03:31 UTC, nagomuohta commented on app/views/users/_headersigninfive.html.haml
> +%header.users_signin_form_header
お恥ずかしい限りです、ご指摘ありがとうございます。
ファイル名を、そのファイルの用途に合わせて変更させて頂きました。
例）signinfour →　signincredit　　（クレジットカード登録画面）
       signinfive  →　signincomplete （登録完了画面）

2019-02-06 03:38 UTC, miyagit reviewed
全体的にアンバサンドを使っていなかったり、インデントがおかしかったり、ハッシュロケットを使っていたりとするので、もう一度見直してください。

2019-02-06 03:38 UTC, miyagit commented on app/views/users/_headersignincomplete.html.haml
> +    %a.users_signin_form_a{:href => "https://www.mercari.com/jp/"}
ハッシュロケットを直しましょう。
link_toを使いましょう。

2019-02-06 03:38 UTC, miyagit commented on app/views/users/_headersignincomplete.html.haml
> +      %img.users_signin_form_img{:alt => "mercari", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3708647559"}/
ハッシュロケットをやめましょう。
image_tagを使いましょう。

2019-02-06 05:50 UTC, nagomuohta commented on app/views/users/_headersignincomplete.html.haml
> +      %img.users_signin_form_img{:alt => "mercari", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3708647559"}/
修正しました

2019-02-06 05:50 UTC, nagomuohta commented on app/views/users/_headersignincomplete.html.haml
> +    %a.users_signin_form_a{:href => "https://www.mercari.com/jp/"}
修正しました

2019-02-06 05:56 UTC, yusukeyamane commented on app/assets/stylesheets/application.scss
> +@import "layout/headersignininformation";
ファイル名がすごく長くなっていて可読性が低いので
> header_signin_in_formation

などとしてスネークケースを使うか、headerとsigninでフォルダーを作って管理した方が検索性も高いです。
今回はいいですが、次回から気をつけましょう！

2019-02-06 05:58 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +  def signininformation
Rubyでは熟語はスネークケースで記述しましょう！

2019-02-06 06:12 UTC, merged