Create item-description html
nagomuohta/freemarket_sample_43d pull request #6
Opened 2019-02-01 04:26 UTC by Daichi1129

2019-02-01 04:32 UTC, Daichi1129 commented
【WHAT】
商品詳細ページの作成

【WHY】
ユーザーが商品を確認、購入することができるようにするため

【ご依頼】
最新のコミットである「create item-description view」が今回作成したビューの変更点になります。
そちらをご確認いただきますよう、お願い申し上げます。

【Viewイメージ】
<img width="1438" alt="2019-02-01 13 31 56" src="https://user-images.githubusercontent.com/46099344/52102804-d161be00-2625-11e9-8540-311c8febf89e.png">
<img width="1440" alt="2019-02-01 13 32 02" src="https://user-images.githubusercontent.com/46099344/52102810-d45cae80-2625-11e9-935e-eb21ade8483c.png">

2019-02-01 04:45 UTC, TOMARUMARU reviewed
scssファイルにて&記法を使って書き直せるところが多々ありますので、見直して修正してみてください！

2019-02-01 06:55 UTC, Daichi1129 commented
&記法の活用等により、リファクタリングいたしました。

2019-02-01 07:00 UTC, hirozak commented on app/views/test/mypage_identification.html.haml
> +              %option{:value => "1900"} 1900
ベタ打ちは避けて繰り返し処理したいです

2019-02-01 07:59 UTC, Daichi1129 commented on app/views/test/mypage_identification.html.haml
> +              %option{:value => "1900"} 1900
javascript のfor文を使って表示させるようにいたしました。

2019-02-01 08:04 UTC, yuki-uchida requested changes
修正お願いします！

2019-02-01 08:04 UTC, yuki-uchida commented on app/assets/stylesheets/mypage_identification.scss
> +.mypage_identification_header_header{
アンバサンドが使えますね。BEMに沿っている利点なので、ぜひ活用して簡潔に書きましょう
全体的に見直して見てください

2019-02-01 08:04 UTC, yuki-uchida commented on app/views/test/mypage_identification.html.haml
> +              %option{:value => ""} --
こちらのあたり、jsではなくhtmlの時点で繰り返し処理を用いて書きましょう

2019-02-01 08:04 UTC, yuki-uchida commented
あとコンフリクトも起きてしまっているので、修正してください

2019-02-01 09:40 UTC, Daichi1129 commented on app/assets/stylesheets/mypage_identification.scss
> +.mypage_identification_header_header{
&を活用し全体を見直しました

2019-02-01 09:40 UTC, Daichi1129 commented on app/views/test/mypage_identification.html.haml
> +              %option{:value => ""} --
hamlにて繰り返し処理できるように変更いたしました

2019-02-01 09:44 UTC, yuki-uchida commented
コンフリクトがまだ起きてます！！！

2019-02-01 09:45 UTC, yuki-uchida requested changes
修正お願いします

2019-02-01 10:37 UTC, Daichi1129 commented
コンフリクトを解消いたしました。

2019-02-01 10:42 UTC, yuki-uchida requested changes
修正お願いします！

2019-02-01 10:42 UTC, yuki-uchida commented on app/assets/stylesheets/item-description.scss
> +      width:118px;
インデントしましょう

2019-02-01 10:42 UTC, yuki-uchida commented on app/assets/stylesheets/item-description.scss
> +    .item-price{
この辺り、BEMに沿って書き直しましょう

2019-02-01 10:42 UTC, yuki-uchida commented on app/views/test/mypage_identification.html.haml
> +          %option 北海道
配列に入れ、繰り返し処理をしましょう。ymlファイルに保存して起き、rails側で呼び出すなどが一般的です

2019-02-01 11:38 UTC, Daichi1129 commented on app/assets/stylesheets/item-description.scss
> +      width:118px;
修正しました

2019-02-01 11:38 UTC, Daichi1129 commented on app/assets/stylesheets/item-description.scss
> +    .item-price{
修正しました

2019-02-02 03:38 UTC, Daichi1129 commented on app/views/test/mypage_identification.html.haml
> +          %option 北海道
修正いたしました

2019-02-02 03:41 UTC, kuroko918 commented on app/views/test/mypage_identification.html.haml
> +%body.mypage_identification
ここにbodeタグは必要ないです！

2019-02-02 03:41 UTC, kuroko918 commented on app/views/test/item-description.html.erb
> +<body class = item_information_body>
こちらもhaml記法に変更しておきましょう！
またここにもbodyタグは必要ないです！

2019-02-02 03:57 UTC, Daichi1129 commented on app/views/test/mypage_identification.html.haml
> +%body.mypage_identification
bodyタグを削除いたしました！

2019-02-02 03:57 UTC, Daichi1129 commented on app/views/test/item-description.html.erb
> +<body class = item_information_body>
haml記法に変更し、bodyタグを削除いたしました！

2019-02-02 04:24 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-02-02 04:26 UTC, Daichi1129 commented
レビュー有難うございました！！！

2019-02-02 07:40 UTC, merged